# Generated by Django 4.0.6 on 2022-12-26 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(20, 'Excerpt is too short')]),
        ),
    ]
