# Generated by Django 4.0.6 on 2023-01-25 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(20, 'Excerpt is too short')]),
        ),
    ]
